"""
Django settings for tu_entrega_api project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os, json, dj_database_url
from pathlib import Path
from datetime import timedelta
from firebase_admin import credentials
from firebase_admin import initialize_app

from dotenv import load_dotenv
load_dotenv('.env', override=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', default='your secret key')

# SECURITY WARNING: don't run with debug turned on in production!
PRODUCTION = os.getenv("PRODUCTION", "False") == "True"
DEBUG = not PRODUCTION

ALLOWED_HOSTS = [
    "localhost",
    "tuentregabackend.pythonanywhere.com"
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tu_entrega_app.apps.TuEntregaAppConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'fcm_django',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tu_entrega_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tu_entrega_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if PRODUCTION:
    DATABASES = {
        'default': dj_database_url.config(
                default=os.environ.get('DATABASE_URL'),
                conn_max_age=600,
                ssl_require=True,
                engine='django.db.backends.postgresql'
            )
    }

MIGRATION_MODULES = {
    'tu_entrega_app': 'tu_entrega_app.models.migrations',
}

AUTH_USER_MODEL = "tu_entrega_app.User"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # Default primary key field type

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'tu_entrega_api/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'tu_entrega_api/staticfiles')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Debe estar presente
    ),

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema'
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),  # Ajusta según necesites
    'REFRESH_TOKEN_LIFETIME': timedelta(days=15),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Tu Entrega API',
    'DESCRIPTION': 'Tu Entrega project API Documents',
    'VERSION': '0.0.1',
    'SCHEMA_PATH_PREFIX': '/*',   #To separate routes in urls so they don't mix together.
    # 'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAdminUser'],  # Must login first
    'DISABLE_ERRORS_AND_WARNINGS': True,
    # 'SERVE_AUTHENTICATION': [
    #                 'rest_framework.authentication.SessionAuthentication',
    #             ]
}

JAZZMIN_SETTINGS = {
    "site_logo": "",
    "site_icon": "",
    "login_logo": ""
}


try:
    firebase_config = os.environ.get('FCM_SERVER_KEY')
    if firebase_config is not None:
        firebase_config = json.loads(firebase_config)
        cred = credentials.Certificate(firebase_config)
        FIREBASE_APP = initialize_app(cred)

    FCM_DJANGO_SETTINGS = {
        # an instance of firebase_admin.App to be used as default for all fcm-django requests
        # default: None (the default Firebase app)
        "DEFAULT_FIREBASE_APP": FIREBASE_APP,
        # default: _('FCM Django')
        # "APP_VERBOSE_NAME": "[string for AppConfig's verbose_name]",
        # true if you want to have only one active device per registered user at a time
        # default: False
        "ONE_DEVICE_PER_USER": False,
        # devices to which notifications cannot be sent,
        # are deleted upon receiving error response from FCM
        # default: False
        "DELETE_INACTIVE_DEVICES": True
    }
except:
    pass