# Generated by Django 6.0.7 on 2026-07-22 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_entrega_app', '0003_messenger_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_players', to=settings.AUTH_USER_MODEL)),
                ('player_blocker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocking_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('player_blocker', 'player_blocked'), name='player_can_only_block_other_player_once')],
            },
        ),
    ]
