# Generated by Django 6.0.7 on 2026-07-23 17:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_entrega_app', '0004_blockplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+{1}?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('currency', models.IntegerField(choices=[(1, 'USD'), (2, 'CUP')], db_index=True, default=1)),
                ('payment_method', models.IntegerField(choices=[(1, 'Efectivo'), (2, 'CUP')], db_index=True, default=1)),
                ('price_save', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_contact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='collection_contact', to='tu_entrega_app.contact')),
                ('delivery_contact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='delivery_contact', to='tu_entrega_app.contact')),
            ],
        ),
    ]
