# Generated by Django 6.0.7 on 2026-07-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_entrega_app', '0005_contact_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
