# Generated by Django 6.0.7 on 2026-07-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_entrega_app', '0006_alter_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Transferencia')], db_index=True, default=1),
        ),
    ]
