# Generated by Django 6.0.7 on 2026-07-27 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_entrega_app', '0007_alter_ticket_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='messenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='messenger_tickets', to='tu_entrega_app.messenger'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='owner_tickets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
