# Generated by Django 6.0.7 on 2026-07-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_entrega_app', '0008_ticket_messenger_ticket_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aceptado'), (3, 'En Camino'), (4, 'Entregado'), (5, 'Cancelado')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ManyToManyField(blank=True, related_name='status_ticket', to='tu_entrega_app.status_ticket'),
        ),
    ]
