# Generated by Django 6.0.7 on 2026-07-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_entrega_app', '0009_status_ticket_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('messenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_available', to='tu_entrega_app.messenger')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='messenger_available_list',
            field=models.ManyToManyField(blank=True, related_name='messengers_available', to='tu_entrega_app.messengeravailable'),
        ),
    ]
