# Generated by Django 6.0.7 on 2026-08-11 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_entrega_app', '0011_alter_messenger_km_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Pagado'), (3, 'Cancelado')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'En Proceso'), (3, 'Completado'), (4, 'Cancelado')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='messenger',
            name='free_trip',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=9),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('paymentmethod', models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Transferencia')], db_index=True, default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_time', models.DateTimeField(blank=True, null=True)),
                ('currency', models.IntegerField(choices=[(1, 'USD'), (2, 'CUP')], db_index=True, default=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payer_payment', to=settings.AUTH_USER_MODEL)),
                ('status_list', models.ManyToManyField(blank=True, related_name='status_payment', to='tu_entrega_app.status_payment')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(1, 'Recaraga'), (2, 'Promoción'), (3, 'Transferencia'), (4, 'Viajes')], db_index=True, default=1)),
                ('external_id', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_url', models.URLField(blank=True, max_length=1500, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_user', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payer', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='tu_entrega_app.payment')),
                ('status_list', models.ManyToManyField(blank=True, related_name='status_transaction', to='tu_entrega_app.status_transaction')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collector', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
