# Generated by Django 6.0.7 on 2026-08-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_entrega_app', '0012_status_payment_status_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(1, 'Recaraga'), (2, 'Promoción'), (3, 'Transferencia'), (4, 'Viajes'), (5, 'Retiro')], db_index=True, default=1),
        ),
    ]
