# Generated by Django 6.0.7 on 2026-08-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_entrega_app', '0013_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(1, 'Recarga'), (2, 'Promoción'), (3, 'Transferencia'), (4, 'Viajes'), (5, 'Retiro')], db_index=True, default=1),
        ),
    ]
