# Generated by Django 6.0.7 on 2026-08-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_entrega_app', '0014_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
