# Generated by Django 6.0.7 on 2026-08-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tu_entrega_app', '0015_alter_user_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=22, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=22, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='messenger',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=22, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='messenger',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=22, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=22, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=22, max_digits=25, null=True),
        ),
    ]
